% This is an autogenerated sample test for file rockPaperScissors.m
classdef testrockPaperScissors < matlab.unittest.TestCase

    methods (Test)

        function test_rockPaperScissors(testCase)
            % Specify the input(s) of rockPaperScissors
            p1 = "rock";
            p2 = "scissors";

            % Specify the expected output(s) of rockPaperScissors
            expected_result = "Player 1 wins"

            % Exercise the function rockPaperScissors
            actual_result = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actual_result, expected_result);
        end
    end
end